name: AoC 2024 Review
run-name: Running latest changes to AoC 2024 solutions

on: [push]
jobs:
  Verify-Solutions:
    runs-on: ubuntu-latest
    steps:
      - name: Apply personal cookie
        env:
          SESSION: ${{ secrets.SESSION }}
        run: echo "$SESSION" > .session
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Test
        run: ls -a .