name: AoC 2024 Review

on:
  - push
  - workflow_dispatch
jobs:
  setup:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .
            tools
            examples
      - name: Apply personal cookie
        env:
          SESSION: ${{ secrets.SESSION }}
        run: echo "$SESSION" > tools/.session
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Grab Python Packages
        run: pip install -r tools/requirements.txt
      - name: Pull Inputs From Cache
        uses: actions/cache/restore@v4
        with:
          path: inputs
          key: inputs-2024
      - name: Run Script
        id: run-inputs-script
        run: |
          set +e
          python tools/grab_day_inputs.py 2024
          echo "exitcode=$?" >> $GITHUB_OUTPUT
      - name: Save Inputs To Cache
        uses: actions/cache/save@v4
        with:
          path: inputs
          key: inputs-2024
        if: steps.run-inputs-script.outputs.exitcode > 0
      - name: Push to Artifacts
        id: push-answers
        uses: actions/upload-artifact@v4
        with:
          name: answers
          path: |
            *.py
            *.txt
            inputs/*.txt
            examples/*.txt
          if-no-files-found: error
          compression-level: 9
          overwrite: true
          retention-days: 1

  linting:
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - name: Pull from Artifacts
        uses: actions/download-artifact@v4
        with:
          name: answers
          merge-multiple: true
      - name: Linting
        uses: astral-sh/ruff-action@v2
        with:
          version: "0.8.2"
          args: check --exit-zero --output-format=github

  testing:
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - name: Pull from Artifacts
        uses: actions/download-artifact@v4
        with:
          name: answers
          merge-multiple: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Grab Python Packages
        run: pip install --upgrade pytest
      - name: Execute Unit Tests
        run: pytest -v --color=yes --junit-xml=test_report.xml *.py
      - name: Upload Test Report
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: test_report.xml
          check_name: Daily Results
    permissions:
      checks: write

  cleanup:
    needs: [setup, linting, testing]
    if : always()
    runs-on: ubuntu-24.04
    steps:
      - name: Clean Up Mid-Job Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: answers
          failOnError: false
