name: AoC 2024 Review
run-name: Running latest changes to AoC 2024 solutions

on:
  - push
  - workflow_dispatch
jobs:
  Verify-Solutions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .
            tools
      - name: Apply personal cookie
        env:
          SESSION: ${{ secrets.SESSION }}
        run: echo "$SESSION" > tools/.session
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: pip
      - name: Grab Python Packages
        run: pip install -r tools/requirements.txt
      - name: Retrieve Daily Inputs
        uses: actions/cache/restore@v4
        with:
          path: inputs
          key: inputs-2024
      - name: Run Script
        id: run-inputs-script
        run: |
          set +e
          python tools/grab_day_inputs.py 2024
          echo "exitcode=$?" >> $GITHUB_OUTPUT
      - name: Save Daily Inputs
        uses: actions/cache/save@v4
        with:
          path: inputs
          key: inputs-2024
        if: steps.run-inputs-script.outputs.exitcode > 0
