name: AoC 2024 Review
run-name: Running latest changes to AoC 2024 solutions

on:
  - push
  - workflow_dispatch
jobs:
  Verify-Solutions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .
            tools
      - name: Apply personal cookie
        env:
          SESSION: ${{ secrets.SESSION }}
        run: echo "$SESSION" > tools/.session
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: pip
      - name: Grab Python Packages
        run: pip install -r tools/requirements.txt
      - name: Run Script
        run: python tools/grab_day_inputs.py 2024
